added support for dynamic feature support
newrelic/newrelic-android-agent pull request #184
Opened 2024-02-26 19:53 UTC by ndesai-newrelic

1) added support for dynamic feature
2) fixed smoke tests for plugin smoke test

2024-02-27 00:04 UTC, ndesai-newrelic commented
ran smoke tests with map upload task test: https://github.com/newrelic/newrelic-android-agent/actions/runs/8057287789/job/22008085587

2024-02-27 16:34 UTC, cthomas-newrelic requested changes
Let's restart this PR from scratch. Too many unnecessary changes. I'll have time to pair today with you on it.

2024-02-27 17:17 UTC, ndesai-newrelic commented on gradle.properties
> -newrelic.agent.version = 7.2.1
@cthomas-newrelic i added that intentionally so i can run smoke test on my branch, otherwise it will fetch agent from maven.

2024-02-27 17:19 UTC, ndesai-newrelic commented on plugins/README.md
> +When applied to an Android project, the New
i can remove this.

2024-02-27 17:20 UTC, ndesai-newrelic commented on samples/agent-test-app/gradle.properties
> -
i can fix this.

2024-02-27 17:33 UTC, cthomas-newrelic commented on gradle.properties
> -newrelic.agent.version = 7.2.1
Yes, that's what we all do., just not when merging back. All (at least most) of the actions can be started with a specific branch from the UI.

2024-02-27 17:34 UTC, ndesai-newrelic commented on gradle.properties
> -newrelic.agent.version = 7.2.1
got it.

2024-02-27 22:38 UTC, ndesai-newrelic commented on samples/agent-test-app/feature/build.gradle
> +if (project.applyPlugin && Boolean.valueOf(project.applyPlugin)) {
need to check

2024-02-27 23:56 UTC, ndesai-newrelic commented on samples/agent-test-app/feature/build.gradle
> +if (project.applyPlugin && Boolean.valueOf(project.applyPlugin)) {
@cthomas-newrelic removed it in latest push

2024-02-29 04:00 UTC, cthomas-newrelic approved these changes
Please squash merge, looks good!

2024-02-29 14:08 UTC, merged